a = input('Digite algo: ')
print('')
print('O tipo primitivo desse valor é ',type(a))
print('Só tem espaços: ', a.isspace())
print('É um número?: ', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Ésta em maiúsculas?', a.isupper())
print('Ésta em ninúsculas?', a.islower())
print('Ésta captalizada?', a.istitle())
